# -*- coding: utf-8 -*-
"""regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w73PhmF0EzyQ__z29fBzyEs1qzn68uif
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split

np.random.seed(42)
X_line = 10 * np.random.rand(100,1)
y_line = 2 * X_line.ravel() + 1 + np.random.randn(100) *2

X_train_l, X_test_l, y_train_l, y_test_l = train_test_split(X_line, y_line, test_size=0.2)

lin_reg = LinearRegression().fit(X_train_l, y_train_l)
svr_lin =SVR(kernel='linear').fit(X_train_l, y_train_l)

y_pred_lin = lin_reg.predict(X_test_l)
y_pred_svr = svr_lin.predict(X_test_l)

print ("----- BEST FIT LINE METRICS -----")
print (f"Linear Regression MSE: {mean_squared_error(y_test_l, y_pred_lin):.2f}, R2: {r2_score(y_test_l, y_pred_lin):.2f}")
print(f"SVM Reg MSE: {mean_squared_error(y_test_l, y_pred_svr):.2f}, R2: {r2_score(y_test_l, y_pred_svr):.2f}")

plt.figure(figsize=(8,5))
plt.scatter(X_line, y_line, color='gray', alpha=0.5, label='Data')
plt.plot(X_line, lin_reg.predict(X_line), color='red', label='Linear Best Fit Line')
plt.plot(X_line, svr_lin.predict(X_line), color='blue', linestyle='--', label='SVM Best Fit Line')
plt.legend()
plt.title("Linear vs SVM regression best fit line")
plt.show()

"""Let's check the information about the dataset to understand its columns, data types, and non-null values."""

import pandas as pd

# Load the housing dataset, specifying space as a separator and no header
housing_df = pd.read_csv('/content/housing.csv', sep=r'\s+', header=None)

# Display the first 5 rows of the DataFrame
display(housing_df.head())
housing_df.info()

# Define column names for the Boston Housing Dataset
column_names = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV']

# Assign column names to the DataFrame
housing_df.columns = column_names

# Display the first 5 rows with new column names
display(housing_df.head())

# Display info to confirm column names and data types
housing_df.info()

# Define features (X) and target (y)
X = housing_df.drop('MEDV', axis=1)
y = housing_df['MEDV']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Shape of X_train:", X_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of y_test:", y_test.shape)

lin_reg_housing = LinearRegression()
lin_reg_housing.fit(X_train, y_train)


svr_housing = SVR(kernel='linear')
svr_housing.fit(X_train, y_train)

print("Linear Regression model trained.")
print("SVM Regressor model trained.")

y_pred_lin_housing = lin_reg_housing.predict(X_test)
y_pred_svr_housing = svr_housing.predict(X_test)


mse_lin_housing = mean_squared_error(y_test, y_pred_lin_housing)
r2_lin_housing = r2_score(y_test, y_pred_lin_housing)


mse_svr_housing = mean_squared_error(y_test, y_pred_svr_housing)
r2_svr_housing = r2_score(y_test, y_pred_svr_housing)

print("----- HOUSING DATASET METRICS -----")
print(f"Linear Regression MSE: {mse_lin_housing:.2f}, R2: {r2_lin_housing:.2f}")
print(f"SVM Regressor MSE: {mse_svr_housing:.2f}, R2: {r2_svr_housing:.2f}")

